import { NextResponse } from 'next/server'
import { passwordResetDb } from '@/lib/database'

export async function POST(req: Request) {
  try {
    const body = await req.json()
    const { email, code } = body || {}

    console.log(`[Verify Code] Request for email: ${email}, code: ${code}`)

    if (!email || !code) {
      console.log(`[Verify Code] Missing email or code`)
      return NextResponse.json({ success: false, error: 'Missing email or code' }, { status: 400 })
    }

    const record = await passwordResetDb.findValid(email, code)
    if (!record) {
      console.log(`[Verify Code] Invalid or expired code for ${email}`)
      return NextResponse.json({ success: false, error: 'Invalid or expired code' }, { status: 400 })
    }

    console.log(`[Verify Code] Code verified for ${email}`)
    // Consume the code so it cannot be reused
    await passwordResetDb.consume(email, code)
    console.log(`[Verify Code] Code consumed for ${email}`)

    // Return the reset URL (generated by better-auth) so client can redirect to it
    return NextResponse.json({ success: true, resetUrl: record.resetUrl })
  } catch (err: any) {
    console.error(`[Verify Code] Error:`, err)
    return NextResponse.json({ success: false, error: err?.message || 'Server error' }, { status: 500 })
  }
}
